swagger: '2.0'
info:
  description: 'This API returns data regarding the descriptions of almost all nouns in vedic literature. The results are JSON objects that contain the word transliterated to roman, the word in nagari, the meaning of the word, and the category the word belongs to.'
  title: vs API
  version: '1.1'
  license:
    name: 'Distributed under the MIT license'
    url: 'https://opensource.org/licenses/MIT'
  contact:
    email: 'ab.techwriter@gmail.com'
externalDocs:
  description: 'Documentation'
  url: 'https://aninditabasu.github.io/indica/'
host: sheetlabs.com
schemes:
  - https
basePath: /IND/vs
paths:
  /:
    get:
      summary: 'Fetch all records from the database'
      responses:
        '200':
          description: 'Records fetched'
        '401':
          description: 'The API needs an authentication key.'
  /word:
    get:
      summary: 'Fetch the meaning of a specific Sanskrit word'
      parameters:
        - in: query
          name: word
          type: string
          required: true
          description: 'The Sanskrit word transliterated into English, for example, rajan. Wildcards are allowed, for example, \*aj\*.'
      responses:
        '200':
          description: 'Word meaning fetched successfully.'
        '401':
          description: 'You need an authentication key.'
        '404':
          description: 'No such word exists in the database.' 
  /description:
    get:
      summary: 'Fetch all meanings that contain a specific English word'
      parameters:
        - in: query
          name: description
          type: string
          required: true
          description: 'The string you are looking for in the word meaning, for example, chariot. Wildcards are allowed, for example, char\*.'
      responses:
        '200':
          description: 'Words fetched successfully.'
        '401':
          description: 'You need an authentication key.'
        '404':
          description: 'This string does not exist in the database.'
  /category:
    get:
      summary: 'Fetch all words in a specific category'
      parameters:
        - in: query
          name: category
          type: string
          enum:
            - grass
            - plant
            - tree
            - animal
            - bird
            - cattle
            - fish
            - insect
            - snake
            - worm
            - building
            - chariot
            - food
            - grain
            - metal
            - object
            - ship
            - weapon
            - war
            - number
            - distance
            - time
            - weight
            - mountain
            - place
            - river
            - astronomy
            - disease
            - literature
            - medicine
            - poison
            - subject
            - dicing
            - games
            - music
            - clothing
            - hair
            - ornament
            - law
            - morals
            - agriculture
            - caste
            - family
            - occupation
            - priest
            - royalty
            - trade
            - tribe
          required: true
          description: 'Click to select from a list'
      responses:
        '200':
          description: 'Words fetched successfully.'
        '401':
          description: 'You need an authentication key.'
        '404':
          description: 'No such category exists in this API.'