swagger: '2.0'
info:
  description: | 
    # Introduction
    This API returns data regarding almost all nouns in vedic literature. The results are JSON objects that contain the word transliterated to the Roman script, the word in the Nagari script, the meaning of the word, and the category the word belongs to. Proper nouns are not included (yet).
    
    The API uses the Swagger 2.0 specification.
    
    # Authentication
    This is an open API.
    
    # Try it out
    This sandbox can be used to get data for only one kind of resource, that is, to fetch data for a string contained in the meaning of any of the words.
    
    The remaining resources work a similar fashion. For details, see the reference documentation.
  title: vs API
  version: '1.2'
  x-logo:
    url: 'https://raw.githubusercontent.com/AninditaBasu/indica/gh-pages/favicon.ico'
    altText: 'Indica logo'
  license:
    name: 'Distributed under the MIT license'
    url: 'https://opensource.org/licenses/MIT'
  contact:
    email: 'ab.techwriter@gmail.com'
externalDocs:
  description: 'Documentation'
  url: 'https://aninditabasu.github.io/indica/'
host: api-vs.herokuapp.com
schemes:
  - https
basePath: /vs/v1
paths:
  /resources:
    get:
      summary: 'Fetch all meanings that contain a specific English string'
      parameters:
        - in: query
          name: description
          type: string
          required: true
          description: 'The string you are looking for in the word meaning, for example, chariot. Wildcards are allowed, for example, char\*.'
      responses:
        '200':
          description: 'Entries fetched.'
        '404':
          description: 'No such string exists in this API.'
