swagger: '2.0'
info:
  description: | 
    # Introduction
    This API returns data regarding almost all nouns in vedic literature. The results are JSON objects that contain the word transliterated to the Roman script, the word in the Nagari script, the meaning of the word, and the category the word belongs to. Proper nouns are not included (yet).
    
    The API uses the Swagger 2.0 specification.
    
    # Authentication
    This is an open API.
    
    # Rate limits
    Total monthly calls are limited to 10,000.
  title: vs API
  version: '1.1'
  x-logo:
    url: 'https://AninditaBasu.github.io/images/indica.png'
    altText: 'Indica logo'
  license:
    name: 'MIT License'
    url: 'https://opensource.org/licenses/MIT'
  contact:
    email: 'ab.techwriter@gmail.com'
externalDocs:
  description: 'Documentation'
  url: 'https://aninditabasu.github.io/indica/'
host: sheetlabs.com
schemes:
  - https
basePath: /IND/vs
paths:
  /:
    get:
      summary: 'Fetch all entries in this API'
      responses:
        '200':
          description: 'Entries fetched'
        '404':
          description: 'No entry found'
  /word:
    get:
      summary: 'Fetch the meaning of a specific Sanskrit word'
      parameters:
        - in: query
          name: word
          type: string
          required: true
          description: 'The Sanskrit word transliterated into English, for example, rajan. Wildcards are allowed, for example, \*aj\*.'
      responses:
        '200':
          description: 'Entries fetched.'
        '404':
          description: 'No such word exists in this API.'
  /description:
    get:
      summary: 'Fetch all meanings that contain a specific English string'
      parameters:
        - in: query
          name: description
          type: string
          required: true
          description: 'The string you are looking for in the word meaning, for example, chariot. Wildcards are allowed, for example, char\*.'
      responses:
        '200':
          description: 'Entries fetched.'
        '404':
          description: 'No such string exists in this API.'
  /category:
    get:
      summary: 'Fetch all words in a specific category'
      parameters:
        - in: query
          name: category
          type: string
          enum:
            - grass
            - plant
            - tree
            - animal
            - bird
            - cattle
            - fish
            - insect
            - snake
            - worm
            - building
            - chariot
            - food
            - grain
            - metal
            - object
            - ship
            - weapon
            - war
            - number
            - distance
            - time
            - weight
            - mountain
            - place
            - river
            - astronomy
            - disease
            - literature
            - medicine
            - poison
            - subject
            - dicing
            - games
            - music
            - clothing
            - hair
            - ornament
            - law
            - morals
            - agriculture
            - caste
            - family
            - occupation
            - priest
            - royalty
            - trade
            - tribe
          required: true
          description: 'Click to select from a list'
      responses:
        '200':
          description: 'Entries fetched.'
        '404':
          description: 'No such category exists in this API.'