title: Indica APIs
author: Anindita Basu
description: JSON dictionaries of data from ancient India. Includes data from Mahabharat, metadata from Rig Veda, descriptions of all nouns in vedic literature.
github:
  repository_url: https://github.com/AninditaBasu/indica

remote_theme: AninditaBasu/ledger

plugins:
  - jekyll-remote-theme

ledger:
  preset: palmleaf

copyright_start: 2018

kramdown:
  toc_levels: 2..3
  auto_ids: true