title: Indica APIs
author: Anindita Basu
description: JSON dictionaries of data from ancient India. Includes metadata of all the verses in Rig Veda (rishis, gods, chhandas) and a description of all nouns in vedic literature (including the flora, fauna, geography, food, relationships, and objects).
github:
  repository_url: https://github.com/AninditaBasu/indica

remote_theme: AninditaBasu/ledger

plugins:
  - jekyll-remote-theme

ledger:
  preset: palmleaf


