site_name: The Indica APIs
site_description: JSON data from ancient India through APIs
copyright: '&copy; 2018-2022 Anindita Basu.'
#
docs_dir: docs
#
nav:
- 'Home': 'index.md'
- API reference:
    - 'Rig Veda API': 'api_rv.md'
    - 'Vedic Society API': 'api_vs.md'
- Tutorials:
    - 'Vedic soliloquies': 'how_to_soliloquy.md'
- Live sandbox:
    - 'Rig Veda API': 'rv_meta_openapi3.html'
    - 'Vedic Society API': 'vs_openapi3.html'
#
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/anindita_basu
      name: Anindita on Twitter
  analytics:
    provider: google
    property: G-2FQGMZ1ZEN

# ===============================
# mkdocs-material theme entries start here
# https://squidfunk.github.io/mkdocs-material/getting-started/
#
theme:
    name: material
    language: en
    favicon: images/favicon.ico
    custom_dir: overrides
    palette:
      primary: orange
      accent: green
# mkdocs-material theme entries end here
# ===============================

#
# Extensions list (https://squidfunk.github.io/mkdocs-material/reference/abbreviations/):
#  - meta, which is part of the standard Markdown library, and is for front matter in a doc file
#  - admonition, which is part of the standard Markdown library, and is for notes and warnings
#  - attr_list, which enables the adding of HTML attributes and CSS classes to several Markdown elements
#  - def_list, which is part of the standard Markdown library, and is for definition lists
#  - pymdownx.tabbed, which is part of Python Markdown Extensions, and is used for tabbed content blocks
#  - pymdownx.superfences, which is part of the standard Markdown library, and is for syntax highlighting of code blocks.
#  - pymdownx.highlight, which is part of the standard Markdown library, and is for rendering line numbers as part of the line itself
#  - pymdownx.details, which supercharges the Admonition extension, making the resulting call-outs collapsible
#  - pymdownx.tasklist, which is part of Python Markdown Extensions and shows lists with styled checkboxes
#  - toc, which is a Material for Mkdocs extension for the page-level ToC header
#  - ...
markdown_extensions:
  - meta
  - admonition
  - attr_list
  - def_list
  - toc:
      title: On this page
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
#
# Plug-ins list:
# - search, an in-built MkDocs plug-in for search
# - macros, for jinja style includes, variables, and conditions (https://github.com/fralau/mkdocs_macros_plugin) 
# - tags, for tagging pages for better search (https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/)
# - ...
plugins:
    - search
    - macros
    - tags
# end of mkdocs config file