swagger: '2.0'
info:
  description: | 
    # Introduction
    This API returns information about all of the verses in Rig Veda. The results are JSON objects that contain the name of the god, poet, and meter of the verses in Rig Veda, the category of the god and the poet, and the _mandal_ and _sukta_ number.
    
    The API uses the Swagger 2.0 specification.
    
    # Authentication
    This is an open API.
    
    # Try it out
    This sandbox can be used to get data for only one kind of resource, that is, to fetch the data for a category being sung to.
    
    The remaining resources work a similar fashion. For details, see the reference documentation.
  title: rv API
  version: '1.2'
  x-logo:
    url: 'https://raw.githubusercontent.com/AninditaBasu/indica/gh-pages/favicon.ico'
    altText: 'Indica logo'
  license:
    name: 'Distributed under the MIT license'
    url: 'https://opensource.org/licenses/MIT'
  contact:
    email: 'ab.techwriter@gmail.com'
externalDocs:
  description: 'Documentation'
  url: 'https://aninditabasu.github.io/indica/'
host: api-rv.herokuapp.com
schemes:
  - https
basePath: /rv/v1
paths:
  /resources:
    get:
      summary: 'Fetch all verses sung for a specific category of god, person, or object'
      parameters:
        - in: query
          name: sungforcategory
          type: string
          enum:
            - abstract
            - animal
            - demon male
            - divine female
            - divine human
            - divine male
            - human couple
            - human female
            - human male
            - human unborn
            - object
            - plant
          required: true
          description: 'Click to select one of these available values.'
      responses:
        '200':
          description: 'Verses fetched.'
        '404':
          description: 'No verses found.'
