swagger: '2.0'
info:
  description: | 
    # Introduction
    This API returns information about all of the verses in Rig Veda. The results are JSON objects that contain the name of the god, poet, and meter of the verses in Rig Veda, the category of the god and the poet, and the _mandal_ and _sukta_ number.
    
    The API uses the Swagger 2.0 specification.
    
    # Authentication
    This is an open API.
    
    # Rate limits
    Total monthly calls are limited to 10,000.
  title: rv API
  version: '1.1'
  x-logo:
    url: 'https://AninditaBasu.github.io/images/indica.png'
    altText: 'Indica logo'
  license:
    name: 'Distributed under the MIT license'
    url: 'https://opensource.org/licenses/MIT'
  contact:
    email: 'ab.techwriter@gmail.com'
externalDocs:
  description: 'Documentation'
  url: 'https://aninditabasu.github.io/indica/'
host: sheetlabs.com
schemes:
  - https
basePath: /IND/rv
paths:
  /:
    get:
      summary: 'Fetch all entries in this API'
      responses:
        '200':
          description: 'Entries fetched'
        '404':
          description: 'No entry found'
  /mandal:
    get:
      summary: 'Fetch all verses in a specific book (mandal)'
      parameters:
        - in: query
          name: mandal
          type: integer
          enum:
            - 1
            - 2
            - 3
            - 4
            - 5
            - 6
            - 7
            - 8
            - 9
            - 10
          required: true
          description: 'Click to select the mandal number from the list.'
      responses:
        '200':
          description: 'Verses fetched.'
        '404':
          description: 'No verses found.'
  /sungby:
    get:
      summary: 'Fetch all verses composed by a specific rishi (poet)'
      parameters:
        - in: query
          name: sungby
          type: string
          required: true
          description: 'The name of the rishi. Wildcard characters allowed, for example \*mitra*'
      responses:
        '200':
          description: 'Verses fetched.'
        '404':
          description: 'No such rishi composed anything that went into the Rig Veda.'
  /sungbycategory:
    get:
      summary: 'Fetch all verses composed by a specific category of poets'
      parameters:
        - in: query
          name: sungbycategory
          type: string
          enum:
            - animal
            - demon male
            - divine female
            - divine male
            - human female
            - human male
          required: true
          description: 'Click to select from the list.'
      responses:
        '200':
          description: 'Verses fetched.'
        '404':
          description: 'No such poet category exists in this API.'
  /sungfor:
    get:
      summary: 'Fetch all verses addressed to a specific god, human, or thing'
      parameters:
        - in: query
          name: sungfor
          type: string
          required: true
          description: 'The name of the god, goddess, or object. Wildcard characters allowed, for example \*dra*'
      responses:
        '200':
          description: 'Verses fetched.'
        '404':
          description: 'No such god or thing have verses in the Rig Veda composed in their honour.'
  /sungforcategory:
    get:
      summary: 'Fetch all verses composed for a specific category of god, human, or thing'
      parameters:
        - in: query
          name: sungforcategory
          type: string
          enum:
            - abstract
            - animal
            - demon male
            - divine female
            - divine human
            - divine male
            - human couple
            - human female
            - human male
            - human unborn
            - object
            - plant
          required: true
          description: 'Click to select from the list.'
      responses:
        '200':
          description: 'Verses fetched.'
        '404':
          description: 'No such category exists in this API.'
  /meter:
    get:
      summary: 'Fetch all verses composed in a specific meter'
      parameters:
        - in: query
          name: meter
          type: string
          required: true
          description: 'The name of the meter. Wildcard characters allowed, for example \*tri*'
      responses:
        '200':
          description: 'Verses fetched.'
        '404':
          description: 'Rig Veda does not have any verses in that meter.'