swagger: '2.0'
info:
  description: 'This API returns information about all of the verses in Rig Veda. The results are JSON objects that contain the name of the god, poet, and meter of the verses in Rig Veda, the category of the god and the poet, and the mandal and sukta number.'
  title: rv API
  version: '1.1'
  license:
    name: 'Distributed under the MIT license'
    url: 'https://opensource.org/licenses/MIT'
  contact:
    email: 'ab.techwriter@gmail.com'
externalDocs:
  description: 'Documentation'
  url: 'https://aninditabasu.github.io/rigVeda/'
host: sheetlabs.com
schemes:
  - https
basePath: /IND/rv
paths:
  /:
    get:
      summary: 'Fetch all records from the database'
      responses:
        '200':
          description: 'Records fetched'
        '401':
          description: 'The API needs an authentication key.'
  /mandal:
    get:
      summary: 'Fetch all verses in a specific book'
      parameters:
        - in: query
          name: mandal
          type: integer
          enum:
            - 1
            - 2
            - 3
            - 4
            - 5
            - 6
            - 7
            - 8
            - 9
            - 10
          required: true
          description: 'Click to select the mandal number from the list.'
      responses:
        '200':
          description: 'Verses fetched successfully.'
        '401':
          description: 'You need an authentication key.'
  /sungby:
    get:
      summary: 'Fetch all verses composed by a specific rishi'
      parameters:
        - in: query
          name: sungby
          type: string
          required: true
          description: 'The name of the rishi. Wildcard characters allowed, for example *mitra'
      responses:
        '200':
          description: 'Verses fetched successfully.'
        '401':
          description: 'You need an authentication key.'
        '404':
          description: 'No such rishi composed anything that went into the Rig Veda.'
  /sungbycategory:
    get:
      summary: 'Fetch all verses composed by a specific category of beings'
      parameters:
        - in: query
          name: sungbycategory
          type: string
          enum:
            - animal
            - demon male
            - divine female
            - divine male
            - human female
            - human male
          required: true
          description: 'Click to select from the list.'
      responses:
        '200':
          description: 'Verses fetched successfully.'
        '401':
          description: 'You need an authentication key.'
        '404':
          description: 'No such poet category exists in this API.'
  /sungfor:
    get:
      summary: 'Fetch all verses addressed to a specific god, goddess, or object'
      parameters:
        - in: query
          name: sungfor
          type: string
          required: true
          description: 'The name of the god, goddess, or object. Wildcard characters allowed, for example *dra'
      responses:
        '200':
          description: 'Verses fetched successfully.'
        '401':
          description: 'You need an authentication key.'
        '404':
          description: 'No such god or thing had verses composed in their honour.'
  /sungforcategory:
    get:
      summary: 'Fetch all verses composed for a specific category'
      parameters:
        - in: query
          name: sungforcategory
          type: string
          enum:
            - abstract
            - animal
            - demon male
            - divine female
            - divine human
            - divine male
            - human couple
            - human female
            - human male
            - human unborn
            - object
            - plant
          required: true
          description: 'Click to select from the list.'
      responses:
        '200':
          description: 'Verses fetched successfully.'
        '401':
          description: 'You need an authentication key.'
        '404':
          description: 'No such category exists in this API.'
  /meter:
    get:
      summary: 'Fetch all verses composed in a specific meter'
      parameters:
        - in: query
          name: meter
          type: string
          required: true
          description: 'The name of the meter. Wildcard characters allowed, for example *tri'
      responses:
        '200':
          description: 'Verses fetched successfully.'
        '401':
          description: 'You need an authentication key.'
        '404':
          description: 'Rig Veda does not have any verses in that meter.'
