openapi: 3.0.0
info:
  version: 1.0.0
  title: Simple Artist API
  description: A simple API to illustrate OpenAPI concepts
servers:
  - url: https://api-rv.herokuapp.com/rv/v1/
paths:
  /resources:
    get:
      description: Returns a list of verses
      parameters:
        - in: query
          name: filter
          required: true
          style: form
          explode: true
          schema:
            type: object
            properties:
              mandal:
                type: integer
                enum:
                  - 1
                  - 2
                  - 3
                  - 4
                  - 5
                  - 6
                  - 7
                  - 8
                  - 9
                  - 10
              sukta:
                type: integer
                minimum: 1
                maximum: 191
              meter:
                type: string
              sungby:
                type: string
              sungbycategory:
                type: string
              sungfor:
                type: string
              sungforcategory:
                type: string
            minProperties: 1
            maxProperties: 1
            additionalProperties: false
      responses:
        '200':
          description: Returned a list
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    mandal:
                      type: integer
                    sukta:
                      type: integer
                    meter:
                      type: string
                    sungby:
                      type: string
                    sungbycategory:
                      type: string
                    sungfor:
                      type: string
                    sungforcategory:
                      type: string
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
